[build]
  publish = "."
  command = "# no build command"

# Redirect and rewrite rules
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Enable Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://unpkg.com https://identity.netlify.com https://cdnjs.cloudflare.com https://fonts.googleapis.com https://fonts.gstatic.com; img-src 'self' data: https://www.precisionfinish.com; style-src 'self' 'unsafe-inline' https://unpkg.com https://cdnjs.cloudflare.com https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com;"